import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#0a0a0a" },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(212,175,55,0.15)",
  },
  brandRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  brandBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#d4af37",
    alignItems: "center",
    justifyContent: "center",
  },
  brandBadgeText: { color: "#0a0a0a", fontWeight: "700" },
  brandName: { color: "#d4af37", fontSize: 20, fontWeight: "700" },
  headerActions: { flexDirection: "row", gap: 16, alignItems: "center" },
  headerAuthSlot: { minWidth: 88, maxWidth: 120, alignItems: "flex-end", justifyContent: "center" },
  headerAuthText: { color: "#d4af37", fontSize: 11, fontWeight: "700", textAlign: "right" },
  headerIcon: { color: "#e8e0d0", fontSize: 20 },
  content: { padding: 20, paddingBottom: 120, gap: 14 },
  tagline: { color: "#9f8950", fontSize: 11, letterSpacing: 2 },
  title: { color: "#e8e0d0", fontSize: 34, fontWeight: "700", lineHeight: 38 },
  gold: { color: "#d4af37" },
  sectionGap: { marginTop: 8 },
  categoryPill: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.2)",
    backgroundColor: "#1a1a1a",
    marginRight: 8,
  },
  categoryPillActive: { backgroundColor: "#d4af37" },
  categoryContent: { flexDirection: "row", alignItems: "center", gap: 6 },
  categoryText: { color: "#e8e0d0", fontSize: 12, fontWeight: "600" },
  featureCard: {
    backgroundColor: "#121212",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.2)",
    padding: 16,
    gap: 8,
  },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  badge: {
    color: "#d4af37",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 1,
    backgroundColor: "rgba(212,175,55,0.1)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: "hidden",
  },
  heart: { fontSize: 18 },
  heroIconWrap: { alignItems: "center", justifyContent: "center", marginVertical: 6 },
  homePreviewHero: {
    width: "100%",
    height: 200,
    borderRadius: 12,
    marginVertical: 8,
    backgroundColor: "#1a1a1a",
    overflow: "hidden",
  },
  homePreviewGrid: {
    width: "100%",
    height: 110,
    borderRadius: 10,
    marginBottom: 6,
    backgroundColor: "#1a1a1a",
    overflow: "hidden",
  },
  homePreviewArrival: {
    width: "100%",
    height: 96,
    borderRadius: 10,
    marginBottom: 6,
    backgroundColor: "#1a1a1a",
    overflow: "hidden",
  },
  homePreviewFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 80,
  },
  itemTitle: { color: "#e8e0d0", fontSize: 21, fontWeight: "700" },
  itemDesc: { color: "#b8b0a1", fontSize: 13, lineHeight: 18 },
  price: { color: "#d4af37", fontSize: 24, fontWeight: "700", marginTop: 4 },
  meta: { color: "#8f8a81", fontSize: 12 },
  metaRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  sectionHeader: { color: "#e8e0d0", fontSize: 22, fontWeight: "700" },
  viewAll: { color: "#d4af37", fontSize: 12, textTransform: "uppercase" },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  gridCard: {
    width: "48%",
    backgroundColor: "#141414",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.1)",
  },
  badgeSmall: {
    color: "#d4af37",
    fontSize: 9,
    backgroundColor: "rgba(212,175,55,0.08)",
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: "hidden",
  },
  cardIconWrap: { alignItems: "center", justifyContent: "center", marginVertical: 8 },
  gridName: { color: "#e8e0d0", fontSize: 13, fontWeight: "600" },
  gridPrice: { color: "#d4af37", fontSize: 13, fontWeight: "700", marginTop: 2 },
  arrivalCard: {
    width: 150,
    backgroundColor: "#141414",
    borderRadius: 14,
    padding: 12,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.1)",
  },
  collectionCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#141414",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.1)",
    marginBottom: 8,
  },
  collectionIconGroup: { flexDirection: "row", gap: 4, alignItems: "center" },
  collectionName: { color: "#e8e0d0", fontSize: 15, fontWeight: "700" },
  dbCategoryWrap: { gap: 10, marginTop: 8 },
  dbCategoryCard: {
    backgroundColor: "#141414",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.1)",
  },
  dbItemList: { gap: 10, marginTop: 8 },
  dbItemCard: {
    backgroundColor: "#141414",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.1)",
    gap: 4,
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "rgba(212,175,55,0.15)",
    backgroundColor: "#0a0a0a",
  },
  bottomItem: { paddingHorizontal: 8, paddingVertical: 6, alignItems: "center", gap: 2 },
  bottomText: { color: "#8f8a81", fontSize: 12, textTransform: "capitalize" },
  modal: { flex: 1, backgroundColor: "#0a0a0a", padding: 20 },
  searchHeader: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 16 },
  input: {
    flex: 1,
    backgroundColor: "#1a1a1a",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.2)",
    color: "#e8e0d0",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#1a1a1a",
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  emptyText: { color: "#777", textAlign: "center", marginTop: 40, fontSize: 14 },
  bigIconWrap: { alignItems: "center", justifyContent: "center", marginVertical: 20 },
  detailTitle: { color: "#e8e0d0", fontSize: 28, fontWeight: "700", marginTop: 12 },
  descriptionCard: {
    backgroundColor: "#171717",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.1)",
    padding: 14,
    marginTop: 14,
  },
  ctaButton: {
    marginTop: 18,
    backgroundColor: "#d4af37",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  ctaText: { color: "#0a0a0a", fontWeight: "700", fontSize: 15 },
  profileStats: { marginTop: 10, gap: 6 },
  toast: {
    position: "absolute",
    top: 80,
    left: 20,
    right: 20,
    backgroundColor: "#1a1a1a",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.2)",
    padding: 14,
    gap: 6,
  },
});
