import { StyleSheet } from "react-native";

export const authModalStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#0a0a0a", padding: 20 },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16 },
  title: { color: "#e8e0d0", fontSize: 22, fontWeight: "700" },
  subtitle: { color: "#8f8a81", fontSize: 14, lineHeight: 20, marginBottom: 18 },
  segmentRow: { flexDirection: "row", marginBottom: 20, gap: 10 },
  segment: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.25)",
    alignItems: "center",
  },
  segmentActive: { backgroundColor: "rgba(212,175,55,0.2)", borderColor: "#d4af37" },
  segmentText: { color: "#b8b0a1", fontSize: 13, fontWeight: "600" },
  segmentTextActive: { color: "#d4af37" },
  label: { color: "#9f8950", fontSize: 11, letterSpacing: 1, marginBottom: 6, textTransform: "uppercase" },
  input: {
    backgroundColor: "#1a1a1a",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.2)",
    color: "#e8e0d0",
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 14,
    fontSize: 15,
  },
  error: { color: "#c44", fontSize: 13, marginBottom: 12 },
  primaryBtn: {
    backgroundColor: "#d4af37",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 6,
  },
  primaryBtnText: { color: "#0a0a0a", fontWeight: "700", fontSize: 15 },
  secondaryBtn: {
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.25)",
    alignItems: "center",
  },
  secondaryBtnText: { color: "#e8e0d0", fontWeight: "600", fontSize: 14 },
  divider: { flexDirection: "row", alignItems: "center", gap: 12, marginVertical: 18 },
  dividerLine: { flex: 1, height: 1, backgroundColor: "rgba(212,175,55,0.15)" },
  dividerText: { color: "#666", fontSize: 12 },
  stepHint: { color: "#d4af37", fontSize: 12, marginBottom: 12, fontWeight: "600" },
  rowGap: { flexDirection: "row", gap: 10 },
  flex1: { flex: 1 },
  backLink: { color: "#d4af37", fontSize: 14, marginBottom: 12, fontWeight: "600" },
});
