import { Platform, StyleSheet } from "react-native";

export const exploreStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#0a0a0a" },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(212,175,55,0.12)",
    gap: 8,
  },
  backHit: { padding: 8, marginLeft: -4 },
  categoryTitle: {
    flex: 1,
    color: "#e8e0d0",
    fontSize: 18,
    fontWeight: "700",
  },
  toolbar: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  toolbarRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  toolbarLabel: { color: "#8f8a81", fontSize: 11, textTransform: "uppercase", letterSpacing: 1 },
  displayToggle: { flexDirection: "row", backgroundColor: "#1a1a1a", borderRadius: 10, padding: 3 },
  displayBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  displayBtnActive: { backgroundColor: "rgba(212,175,55,0.2)" },
  sortScroll: { flexGrow: 0 },
  sortChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.15)",
    backgroundColor: "#141414",
    marginRight: 8,
  },
  sortChipActive: {
    borderColor: "#d4af37",
    backgroundColor: "rgba(212,175,55,0.12)",
  },
  sortChipText: { color: "#b8b0a1", fontSize: 12, fontWeight: "600" },
  sortChipTextActive: { color: "#e8e0d0" },
  listContent: { padding: 16, paddingBottom: 120 },
  gridRow: { justifyContent: "space-between", gap: 10, marginBottom: 10 },
  exploreItemCard: {
    backgroundColor: "#141414",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  exploreItemCardGrid: {
    flex: 1,
    maxWidth: "48%",
    minWidth: "47%",
  },
  exploreItemListRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 12,
  },
  exploreItemTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  exploreItemGridInner: {
    gap: 8,
  },
  exploreItemGridRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  explorePreviewWrap: {
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#1a1a1a",
    position: "relative",
  },
  explorePreviewPagerHint: {
    position: "absolute",
    bottom: 4,
    left: 0,
    right: 0,
    textAlign: "center",
    color: "#e8e0d0",
    fontSize: 10,
    fontWeight: "600",
    ...(Platform.OS === "web"
      ? { textShadow: "0px 1px 3px rgba(0,0,0,0.92)" }
      : {
          textShadowColor: "#000",
          textShadowOffset: { width: 0, height: 1 },
          textShadowRadius: 3,
        }),
  },
  explorePreviewEmpty: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1a1a1a",
  },
  exploreItemTitle: { color: "#e8e0d0", fontSize: 15, fontWeight: "700" },
  exploreItemMeta: { color: "#8f8a81", fontSize: 12 },
  exploreTapHint: { color: "#6a6a6a", fontSize: 10, marginTop: 4 },
  modalRoot: { flex: 1, backgroundColor: "#0a0a0a" },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(212,175,55,0.12)",
  },
  modalTitle: { flex: 1, color: "#e8e0d0", fontSize: 17, fontWeight: "700", paddingHorizontal: 8 },
  modalGalleryWrap: { paddingVertical: 12 },
  modalHeroImage: { flex: 1, width: "100%", height: "100%", borderRadius: 12, backgroundColor: "#1a1a1a" },
  modalPageHint: { textAlign: "center", color: "#8f8a81", fontSize: 12, marginTop: 8 },
  modalGalleryPlaceholder: { paddingVertical: 24, alignItems: "center" },
  modalBody: { flex: 1, paddingHorizontal: 16, paddingTop: 12 },
  modalRow: { marginBottom: 12, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.06)", paddingBottom: 8 },
  modalKey: { color: "#d4af37", fontSize: 11, textTransform: "uppercase", marginBottom: 4 },
  modalValue: { color: "#e8e0d0", fontSize: 14, lineHeight: 20 },
  emptyList: { color: "#666", textAlign: "center", marginTop: 40, fontSize: 14 },
  categoryCard: {
    backgroundColor: "#141414",
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  categoryCardPressed: {
    opacity: 0.88,
    borderColor: "rgba(212,175,55,0.25)",
  },
});
