import { StyleSheet } from "react-native";

const gold = "#d4af37";
const goldMuted = "rgba(212,175,55,0.35)";
const cream = "#e8e0d0";
const muted = "#8f8a81";
const subtle = "#b8b0a1";
const surface = "#121212";
const surface2 = "#161616";
const border = "rgba(212,175,55,0.18)";

export const profileStyles = StyleSheet.create({
  scroll: { paddingBottom: 120, paddingTop: 8 },
  screenPad: { paddingHorizontal: 20 },

  /* Loading */
  loadWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 100,
    gap: 16,
  },
  loadLabel: { color: muted, fontSize: 14, letterSpacing: 0.3 },

  /* Guest hero */
  guestHero: {
    alignItems: "center",
    paddingVertical: 28,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  guestIconRing: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 2,
    borderColor: goldMuted,
    backgroundColor: surface2,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  guestKicker: { color: gold, fontSize: 11, letterSpacing: 2.5, fontWeight: "600", marginBottom: 8 },
  guestTitle: { color: cream, fontSize: 26, fontWeight: "700", textAlign: "center", lineHeight: 32 },
  guestSubtitle: {
    color: subtle,
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    marginTop: 12,
    maxWidth: 320,
  },
  benefitList: { marginTop: 28, gap: 12, width: "100%", maxWidth: 360, alignSelf: "center" },
  benefitRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: border,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  benefitTextWrap: { flex: 1 },
  benefitTitle: { color: cream, fontSize: 14, fontWeight: "600" },
  benefitDesc: { color: muted, fontSize: 12, marginTop: 3, lineHeight: 16 },
  guestCta: {
    marginTop: 28,
    backgroundColor: gold,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    width: "100%",
    maxWidth: 360,
    alignSelf: "center",
  },
  guestCtaPressed: { opacity: 0.92 },
  guestCtaText: { color: "#0a0a0a", fontWeight: "700", fontSize: 16, letterSpacing: 0.3 },
  guestSecondary: { marginTop: 14, alignItems: "center", paddingVertical: 8 },
  guestSecondaryText: { color: gold, fontSize: 13, fontWeight: "600" },
  wishlistTeaser: {
    marginTop: 32,
    backgroundColor: surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: border,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    maxWidth: 360,
    alignSelf: "center",
    width: "100%",
  },
  wishlistTeaserLeft: { flex: 1, paddingRight: 12 },
  wishlistTeaserLabel: { color: muted, fontSize: 11, letterSpacing: 1.2, fontWeight: "600", marginBottom: 4 },
  wishlistTeaserValue: { color: cream, fontSize: 22, fontWeight: "700" },
  wishlistTeaserHint: { color: muted, fontSize: 12, marginTop: 4 },

  /* Signed-in hero */
  heroCard: {
    backgroundColor: surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: border,
    padding: 22,
    marginBottom: 20,
    overflow: "hidden",
  },
  heroAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: gold,
    opacity: 0.85,
  },
  heroTop: { flexDirection: "row", alignItems: "flex-start", gap: 16 },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#1f1a14",
    borderWidth: 2,
    borderColor: goldMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: gold, fontSize: 24, fontWeight: "700", letterSpacing: 0.5 },
  heroTextBlock: { flex: 1, minWidth: 0 },
  heroName: { color: cream, fontSize: 22, fontWeight: "700", lineHeight: 28 },
  heroUsername: { color: muted, fontSize: 14, marginTop: 4 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(212,175,55,0.12)",
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.28)",
  },
  chipText: { color: gold, fontSize: 11, fontWeight: "700", letterSpacing: 0.8, textTransform: "uppercase" },
  chipRole: {
    backgroundColor: "#141820",
    borderColor: "rgba(140,160,200,0.25)",
  },
  chipRoleText: { color: "#a8b4cc", fontSize: 11, fontWeight: "600", textTransform: "uppercase" },

  sectionLabel: {
    color: muted,
    fontSize: 11,
    letterSpacing: 2,
    fontWeight: "700",
    marginBottom: 10,
    marginTop: 4,
  },
  statRow: { flexDirection: "row", gap: 12, marginBottom: 22 },
  statCard: {
    flex: 1,
    backgroundColor: surface2,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: border,
    padding: 16,
    minHeight: 96,
    justifyContent: "space-between",
  },
  statIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(212,175,55,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  statValue: { color: cream, fontSize: 24, fontWeight: "700", marginTop: 8 },
  statCaption: { color: muted, fontSize: 11, marginTop: 2, letterSpacing: 0.3 },

  detailCard: {
    backgroundColor: surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: border,
    marginBottom: 20,
    overflow: "hidden",
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  detailRowLast: { borderBottomWidth: 0 },
  detailIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: surface2,
    alignItems: "center",
    justifyContent: "center",
  },
  detailBody: { flex: 1, minWidth: 0 },
  detailLabel: { color: muted, fontSize: 11, fontWeight: "600", letterSpacing: 0.6, marginBottom: 3 },
  detailValue: { color: cream, fontSize: 15, lineHeight: 20 },

  signOutWrap: { marginTop: 8, marginBottom: 24 },
  signOutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 15,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(220,100,100,0.45)",
    backgroundColor: "rgba(220,80,80,0.08)",
  },
  signOutPressed: { opacity: 0.88 },
  signOutText: { color: "#e8a0a0", fontSize: 15, fontWeight: "600" },

  pageTitle: { color: cream, fontSize: 13, fontWeight: "600", letterSpacing: 3, marginBottom: 16, opacity: 0.9 },
});
